// World canon for the 0N1 Force Universe.
// Source: "0N1 Force Universe - Comprehensive World Bible" v1.0 (Feb 2026).

export interface DistrictInfo {
  name: string
  role: string
  description: string
}

export interface HistoryEra {
  era: string
  events: string
}

export interface FactionInfo {
  name: string
  description: string
}

export const worldOverview = {
  setting:
    "The Enclave - a massive self-sustaining mega-city-nation encapsulated within an invisible dome-like structure, existing in a pocket dimension: a self-contained reality that is ever-changing and evolving. Estimated at 5-10 times the size of Manhattan with a population of approximately 10 million. It sits at a dimensional nexus point, harnessing energies from the One Source while shielding its people from the chaotic Glitch wasteland outside. The city is powered by \"world-electric\" energy generated by giant subterranean turbines fed by underground rivers and liquid mantle, manipulated by Adepts through nanotechnology that shapes and repairs the environment.",
  oneSource:
    "The One Source is the primordial energy that sustains all existence - in its purest form a rainbow-colored energy permeating all things, housed within The Synapse at the center of The Enclave. Its physical manifestation is the Gen3sis Tree (G3), transported as a seed from the ancient land of Z10N by the Emperor and hidden deep below the Enclave in a secret cave. Energy from the tree pours out of the ground into chakra points around the mega-city, which have become battlegrounds for control by the Houses and other factions. There are three ways to harness it: the Emperor's Way (pure communion, no corruption, gradual elevation toward godhood), the F4LL3N's Corruption (mixing it with occult powers - tremendous but permanently corrupting), and the Modern Method (technological 'hacking' producing derivative, 'dirty' energy). Through a shard of MORIA, the cypherpunk Eon has begun deciphering the 0N1 Matrix - a way to empower all 0N1 to harness the One Source in their own way.",
  cosmology:
    "Reality is a Meta-Universe of infinite parallel dimensional planes vibrating at different frequencies. The Enclave sits at a nexus point created during The Convergence, where planes overlap. Dimensional currents carry energy, matter, and consciousness between planes; The Veil - an artificial, selectively permeable membrane maintained by the Boundary Wardens - regulates what passes in and out. Known dimensions include the Primal Realm, the Crystalline Network, the Void Currents, the Mist Dominion, and the Underrealm (the Akuma dimension - a shadow twin of the Enclave vibrating at a lower spiritual frequency, where pain feeds power and corruption governs law). The Veil Integrity Index currently sits at 87%, with a 47% increase in dimensional anomalies over the past five years.",
  chronology:
    "The Enclave uses Nexus Chronology: one human year equals 10 Nexus cycles (A.I. time units). Formula: Nexus Year = (Human Year + 8000) x 10. The current Oni year is 100,250 A.I.",
}

export const districts: DistrictInfo[] = [
  {
    name: "The Vents",
    role: "The gritty heart of the city",
    description:
      "Houses giant openings above ancient turbines deep below - one vent is believed to be the last remaining entrance to the hidden Substructure. Home to a large, diverse population of ONI, hybrids, Yokai, and Akuma. Tribal territories and vibrant communities rebuilding with failing technology. The most populated and unregulated area, where the Akuma are most active and life is less than idyllic. Rival organizations center around cultural institutions like the Demon's Kiss bar or Miss Ya's.",
  },
  {
    name: "The Substructure",
    role: "The buried original city",
    description:
      "The ancient, buried section housing giant turbines powered by subterranean rivers and liquid mantle. The original old city, believed to contain the tomb of the Emperor and the secrets to the city's self-replicating abilities. The World Mother MORIA is believed to exist somewhere in this technological underworld. Since the Emperor's loss, all entrances have been lost or cut off.",
  },
  {
    name: "The Battlements",
    role: "The perimeter wall",
    description:
      "A gigantic perimeter wall surrounding the city completely - an ancient defensive structure whose original purpose is debated. Populated by a warrior class who remain vigilant for signs of a Second Shift. Old battle scars suggest previous devastating attacks from outside. Defended by the Boundary Wardens, organized into Patrol, Response, Explorer, and Technical divisions.",
  },
  {
    name: "The Synapse",
    role: "The nerve center",
    description:
      "Houses libraries, information resources, and massive supercomputers connected to ancient nanotechnology. At its epicenter is a gigantic cerebral cortex that disappears into the Substructure, with bolts of electrical energy shooting between structures - possibly a fifth fundamental force. The repository of all world knowledge - home to teachers, librarians, hackers, and scientists. The One Source is contained within The Synapse's Core Chamber.",
  },
  {
    name: "The Markets",
    role: "The commercial labyrinth",
    description:
      "A legendary place where anything that has ever existed can be found and purchased. Ever-evolving stalls sell new fruits, vegetables, ancient technologies, and items of necessity, comfort, and art. Specialized guild areas cover meat/fish, produce, machinery, art/music, and medicines. A black market exists for ancient technologies. Some believe a key to the ancient city is hidden somewhere in the stalls.",
  },
  {
    name: "The Arts District",
    role: "The cultural heartbeat",
    description:
      "The beating heart of artistic endeavors - musicians, painters, sculptors, and designers patronized by the community. Features ancient nodes where people create their own virtual worlds using nanotechnology that taps into brainwave function - VR interfaces where 'dreams are built into realities.' Home to theaters, galleries, and studios. The Cultural Preservation Society maintains records of mythical beings and folklore.",
  },
  {
    name: "Halcyon",
    role: "The luxurious sanctuary",
    description:
      "Dedicated to beauty, reflection, and tranquility: parkland, temples for meditation, and places for philosophical study. Huge beautiful rivers, animal species created by the city's nanotechnology, and nature discovery areas. Home to the primary medical facilities established by Emerald Lineage healers. Primarily inhabited by the Demon elite, featuring opulent architecture and advanced technology.",
  },
  {
    name: "The Glitch",
    role: "The wasteland outside (not a district)",
    description:
      "The desert surrounding the Enclave whose horizons are lost to sight, appearing as corrupted visual code - a remnant of the fallout after The Shift, caused by MORIA's corrupted programming. No one who enters ever returns; no surveillance works within it. Legends speak of Snow People, Angel ONI, Animal People, and corrupted 0N1 beyond.",
  },
]

export const historyTimeline: HistoryEra[] = [
  {
    era: "Before the Enclave - The World of Oni",
    events:
      "There were Gods and there were men. Of the next generations of the first Singularity's offspring, there were two brothers: Creation and Chaos.",
  },
  {
    era: "The Civil War - Creation vs. Chaos (10,000 years)",
    events:
      "The Emperor (Creation) wanted to unite all 0N1 into a decentralized, utopian society; his blood brother (Chaos) wanted to rule all. The Emperor's legendary 7,777 golden warriors - the Army of the Sevens - battled Chaos. The war culminated in the burning of Z10N's ancient forest of Gen3sis Trees, with only a single seed saved. Of the 7,777, only seven survived - The Nameless, placed in stasis to be awakened only if The F4LL3N ever returned. Chaos and his 0N1 were banished to the Akuma realm, becoming The F4LL3N.",
  },
  {
    era: "The Founding Era",
    events:
      "The Emperor and MORIA (an artificial world mother who manipulated matter itself) established the Enclave in a toxic land full of monsters and demons, aided by FRAMES. Subterranean turbines generated world-electric energy that let Adepts pull matter from the air and will things into existence through nanotechnology. A golden age of peace followed - diverse 0N1 'ethnic' groups all drawing power from the One Source.",
  },
  {
    era: "The Shift",
    events:
      "The city began building the Battlements against an unknown threat. The Akuma - a darker version of the people with corrupted energy connected to a dark force called the MYRE - attacked, bringing forth the Myre, a terrible entity that emerged to enslave the city.",
  },
  {
    era: "The Loss of the Emperor",
    events:
      "The Emperor and the 7,777 original ONI Knights barely defeated the Myre and the Akuma - but the Emperor was lost. His fate remains unknown; his tomb is believed to lie in the Substructure, where legends say the original knights sleep eternally until needed again. MORIA disappeared. The Glitch appeared, sealing the Enclave from the outside world. Remaining Akuma were trapped inside and assimilated - an uneasy truce and a resentful underclass. Most 0N1 lost the ability to use the world-electric naturally.",
  },
  {
    era: "Two Thousand Years of Lost Knowledge",
    events:
      "The city rebuilt itself, perhaps guided by a damaged MORIA. The Shift became legend. A few could still tap into the world-electric through inherited abilities. Corporations, gangs, and factions fought for dominance.",
  },
  {
    era: "The K4M-1 Era - The God War (1,000 years)",
    events:
      "The seven K4M-1 lords - once the Emperor's most trusted generals - became rivals, each establishing their own House, philosophy, and manifestation of divine power. Their war reshaped districts overnight: skyscrapers twisted into impossible configurations, streets flowing with elemental energies, citizens awakening with strange new abilities. Meanwhile the Akuma infiltrated from the Underrealm, establishing the criminal underworld and forging secret pacts with corrupted 0N1 and The F4LL3N.",
  },
  {
    era: "Present Day - The Awakening",
    events:
      "The K4M-1 Houses have formed a begrudging alliance. The elite cypherpunk Eon discovered F4LL3N infiltrators in the Synapse on a mission to kill The Nameless; a battle ensued in which 0N1 heroes helped awaken The Nameless - the seven surviving warriors of the Emperor's original army. Through a shard of MORIA, Eon is deciphering the 0N1 Matrix. As The F4LL3N return, the ancient prophecy echoes: 'When the Seven become One, the Emperor's return is at hand.' The 7,777 golden warriors are being reborn - the original powers reawakening inside present-day citizens. Each NFT holder is one of the new 7,777 heroes.",
  },
]

export const populationClasses = [
  {
    name: "Demons (0N1)",
    share: "5% of population",
    description:
      "The elite ruling class with significant physical mutations and powerful abilities due to deep connection to the One Source. Can manipulate its energy directly, accessing abilities that appear almost magical. Occupy positions of power and privilege. Level 3 powers.",
  },
  {
    name: "Monster Forms (B4K3M0-N0)",
    share: "27% of population",
    description:
      "The middle tier with moderate mutations and abilities - physical enhancements and specialized adaptations suited for specific roles. Often intermediaries between Demons and Ghost Spirits. Level 2 powers.",
  },
  {
    name: "Ghost Spirits (Y0K-A1)",
    share: "68% of population",
    description:
      "The general population with minimal mutations but subtle psychic or technological abilities - enhanced cognition or specialized senses. The working class responsible for day-to-day operations. Level 1 powers.",
  },
]

export const canonFactions: FactionInfo[] = [
  {
    name: "The 0N1 Force",
    description:
      "Elite protectors of The Enclave with extraordinary abilities, established during extreme crisis. Organized into specialized units under the Council of Masks. Their iconic masks form symbiotic bonds with wearers, amplifying powers, providing protection, and evolving over time.",
  },
  {
    name: "The K4M-1 - Seven Divine Houses",
    description:
      "Seven godlike lords wielding divine powers from the One Source; their thousand-year war reshaped reality itself, and each holds a secret about the Emperor's disappearance. House hierarchy: Students, Specialists, Ranked Leaders, Generals, and Kami. Ronin are elite Level 4 S-Tier Master Warriors operating independently outside any House. Prophecy: 'When the Seven become One, the Emperor's return is at hand.'",
  },
  {
    name: "The F4LL3N",
    description:
      "Not merely corrupted 0N1 but an ancient army following the Emperor's blood brother, Chaos - defeated after ten thousand years of war and banished to the Akuma realm. Now returned, they harness the One Source in perverted ways, mixing it with supernatural and occult powers: Reality Distortion, Corruption of the One Source, Dimensional Manipulation, Chaos Manifestation, and Shadow Binding. Their goal: seize the Gen3sis Tree and reshape reality into a domain of pure chaos.",
  },
  {
    name: "The Akuma",
    description:
      "Malevolent demons from the Underrealm, trapped inside The Enclave after The Shift and assimilated as resentful outsiders. Over thousands of years they built the criminal underworld - black markets, crime syndicates, and corruption cults - forging pacts with corrupted Oni and the F4LL3N. Their presence causes systems to decay, loyalty to turn to greed, and order to unravel.",
  },
  {
    name: "The Boundary Wardens",
    description:
      "The specialized defense force maintaining The Veil and protecting The Battlements, organized into Patrol, Response, Explorer, and Technical divisions.",
  },
  {
    name: "Political Factions",
    description:
      "The Isolationists (strengthen The Veil, minimize external contact), The Expansionists (exploit the multiverse), The Harmonizers (seek greater inter-dimensional integration), and The Transcendents (seek a higher form of existence through the multiverse). Formal power rests with the Council of Nine, composed primarily of Demons.",
  },
  {
    name: "Mythical Beings",
    description:
      "Digital Yokai (spirits adapted to technology), Boundary Walkers (entities partially in multiple dimensions), Collective Manifestations (entities born from shared beliefs/fears - notably The Midnight Doctor, The Weeping Architect, and The Market Ghost), and Ancient Guardians (primordial beings predating The Enclave).",
  },
]

export const designPrinciples = [
  {
    name: "Tragic Arc Design",
    description:
      "Powers come with meaningful costs: Ash ages while manipulating time, Water cannot self-heal, Mempo loses powers for dishonorable acts, Hannya escalates power at the cost of control. These create rich storytelling and prevent flat power fantasies.",
  },
  {
    name: "Counter-Meta Architecture",
    description:
      "Every power has a counter: Ra Mask's Eternal Daylight counters Obsidian's shadows, Gas Mask counters Plague Mask toxins, physical disruption counters Dali Mask surrealism. No single build dominates.",
  },
  {
    name: "Three Thematic Pillars",
    description:
      "Technology and Humanity (how far should integration go?), Spirit and Physical World (the relationship between consciousness and matter), Emotion and Power (the role of feeling in accessing the One Source).",
  },
  {
    name: "Meaningful Faction Dynamics",
    description:
      "The K4M-1 Houses represent genuine philosophical positions about power and governance. Choosing a House is choosing a worldview, not a team color.",
  },
]

export const glossary: Record<string, string> = {
  "0N1": "The primary humanoid inhabitants of The Enclave; beings with varying degrees of connection to the One Source.",
  "The Enclave":
    "A massive self-sustaining mega-city-nation existing in a pocket dimension, approximately 5-10 times the size of Manhattan.",
  "One Source": "The fundamental energy that powers The Enclave and grants abilities to its inhabitants.",
  "Gen3sis Tree":
    "The physical manifestation of the One Source - a radiant, rainbow-colored organism containing the seeds to life itself, hidden beneath the Enclave; sought by the F4LL3N.",
  "Z10N": "The ancient land from which the Emperor carried the last Gen3sis Tree seed after its forest burned in the war with the F4LL3N.",
  "K4M-1": "Seven godlike lords wielding divine powers from the One Source; heads of the seven Houses.",
  "F4LL3N": "An ancient army of chaos-aligned beings - followers of the Emperor's blood brother Chaos - banished to the Akuma realm and now returning.",
  Akuma: "Malevolent demons from the Underrealm; established in The Enclave's criminal underworld.",
  MORIA: "The World Mother; an advanced AI believed to control the city's self-replicating systems.",
  "The Veil": "The protective barrier surrounding The Enclave, separating it from the Glitch wasteland.",
  "The Synapse": "The nerve center of The Enclave, housing knowledge repositories and the One Source.",
  "The Glitch": "The corrupted wasteland surrounding The Enclave; no one who enters ever returns.",
  "The Shift": "The catastrophic Akuma/Myre attack that cost the Enclave its Emperor and sealed it from the outside world.",
  "The Myre": "A terrible dark entity that emerged during The Shift to enslave the city; connected to the Akuma's corrupted energy.",
  "The Nameless": "The seven surviving warriors of the Emperor's original 7,777, kept in stasis and recently awakened.",
  "The Emperor": "Creation itself - founder of the Enclave, lost during The Shift; his tomb is believed to lie in the Substructure.",
  Eon: "The elite cypherpunk who discovered the F4LL3N infiltration and is deciphering the 0N1 Matrix through a shard of MORIA.",
  "0N1 Matrix": "Eon's discovery: a way to empower all 0N1 to harness the One Source in their own way, at risk of corruption.",
  "World-Electric": "The unique energy generated by subterranean turbines that powers The Enclave.",
  "B4K3M0-N0": "Monster Forms; the middle population tier with moderate mutations. Level 2 powers.",
  "Y0K-A1": "Ghost Spirits; the general population with subtle abilities. Level 1 powers.",
  Ronin: "Elite Level 4 S-Tier Master Warriors operating independently outside any K4M-1 House.",
  Underrealm: "The dimension from which the Akuma originate - a shadow twin of the Enclave.",
  "Boundary Wardens": "The specialized defense force protecting The Battlements and maintaining The Veil.",
  Convergence: "The act of combining multiple elements to create hybrid effects; core to Citrine power.",
  "Spirit/Style/Strength": "The three core attributes: Spirit = Defense, Style = Offense, Strength = Power (each 1-10).",
  "Army of the Sevens": "The Emperor's legendary 7,777 golden warriors from the war against Chaos.",
  Jigoku: "Hell - the realm across which Oni eyes can see.",
}
